## Cleaning the Dataset

## Problem Statement
Predict the occurrence and/or severity of wildfires in Algerian regions from meteorological and fire-index features to enable early warning, risk assessment, and resource allocation.

## Features (brief explanation and typical ranges)
- date — date of observation (YYYY-MM-DD)  
- day, month — temporal indicators (day: 1–31, month: 1–12)  
- temperature (°C) — ambient air temperature, typical range ≈ -5 to 45  
- relative_humidity (%) — 0–100  
- wind_speed (m/s) — typical 0–20 (can spike higher)  
- rain (mm) — 0–200 (most observations near 0–20)  
- FFMC (Fine Fuel Moisture Code) — 0–100 (higher = drier fuels)  
- DMC (Duff Moisture Code) — 0–500  
- DC (Drought Code) — 0–1500  
- ISI (Initial Spread Index) — 0–50  
- BUI (Build Up Index) — 0–200  
- FWI (Fire Weather Index) — 0–30  
- fire / burned_area — target: binary (0/1) or continuous (area, e.g., hectares; often 0–1000+)

In [111]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [112]:
dataset = pd.read_csv('./Algerian_forest_fires_dataset_UPDATE.csv' , header=1)
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          246 non-null    str
 1   month        245 non-null    str
 2   year         245 non-null    str
 3   Temperature  245 non-null    str
 4    RH          245 non-null    str
 5    Ws          245 non-null    str
 6   Rain         245 non-null    str
 7   FFMC         245 non-null    str
 8   DMC          245 non-null    str
 9   DC           245 non-null    str
 10  ISI          245 non-null    str
 11  BUI          245 non-null    str
 12  FWI          245 non-null    str
 13  Classes      244 non-null    str
dtypes: str(14)
memory usage: 38.2 KB

In [113]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          246 non-null    str
 1   month        245 non-null    str
 2   year         245 non-null    str
 3   Temperature  245 non-null    str
 4    RH          245 non-null    str
 5    Ws          245 non-null    str
 6   Rain         245 non-null    str
 7   FFMC         245 non-null    str
 8   DMC          245 non-null    str
 9   DC           245 non-null    str
 10  ISI          245 non-null    str
 11  BUI          245 non-null    str
 12  FWI          245 non-null    str
 13  Classes      244 non-null    str
dtypes: str(14)
memory usage: 38.2 KB

In [114]:
dataset.describe()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
count,246,245,245,245,245,245,245,245,245,245,245,245,245,244
unique,33,5,2,20,63,19,40,174,167,199,107,175,128,9
top,01,07,2012,35,55,14,0,88.9,7.9,8,1.1,3,0.4,fire
freq,8,62,244,29,10,43,133,8,5,5,8,5,12,131

## Data Cleaning

In [115]:
## missing values
dataset[dataset.isnull().any(axis=1) ]

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
122,Sidi-Bel Abbes Region Dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,14,07,2012,37,37,18,0.2,88.9,12.9,14.6 9,12.5,10.4,fire,NaN

> The dataset is converted into two sets based on Region from 122th index, we can make a new column based on the Region

-1 : "Bejaia Region Dataset"

-2 : "Sidi-Bel Abbes Region Dataset"

Add new column with region

In [116]:
dataset.loc[:122, "Region"]=0
dataset.loc[122:, "Region"]=1
print(dataset['Region'].dtypes)

float64

In [117]:

# Conver it to int64
dataset[['Region']] = dataset[['Region']].astype(int)
print(dataset['Region'].dtypes)

int64

In [118]:
## Remove the null values from the dataset
dataset = dataset.dropna().reset_index(drop=True)

In [119]:
dataset.isnull().sum()

day            0
month          0
year           0
Temperature    0
 RH            0
 Ws            0
Rain           0
FFMC           0
DMC            0
DC             0
ISI            0
BUI            0
FWI            0
Classes        0
Region         0
dtype: int64

In [120]:
dataset = dataset.drop(122).reset_index(drop=True)

In [121]:
dataset.columns

Index(['day', 'month', 'year', 'Temperature', ' RH', ' Ws', 'Rain ', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes  ', 'Region'],
      dtype='str')

# Fix Spaces in Columns

In [122]:
dataset.columns = dataset.columns.str.strip()
dataset.columns

Index(['day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes', 'Region'],
      dtype='str')

In [123]:
dataset.head()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
0,01,06,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire,0
1,02,06,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire,0
2,03,06,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire,0
3,04,06,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire,0
4,05,06,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire,0

## Change the required column data type

In [124]:
dataset[['day','month','year','Temperature','RH','Ws']] = dataset[['day','month','year','Temperature','RH','Ws']].astype(int)

## Change other columns to float Datatype

In [125]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          243 non-null    int64
 1   month        243 non-null    int64
 2   year         243 non-null    int64
 3   Temperature  243 non-null    int64
 4   RH           243 non-null    int64
 5   Ws           243 non-null    int64
 6   Rain         243 non-null    str
 7   FFMC         243 non-null    str
 8   DMC          243 non-null    str
 9   DC           243 non-null    str
 10  ISI          243 non-null    str
 11  BUI          243 non-null    str
 12  FWI          243 non-null    str
 13  Classes      243 non-null    str
 14  Region       243 non-null    int64
dtypes: int64(7), str(8)
memory usage: 36.1 KB

In [126]:
Objects = [features for features in dataset.columns if dataset[features].dtype == 'str']

In [127]:
for i in Objects:
    # Skip the Classes Feature
    if i !='Classes':
        dataset[i] = dataset[i].astype('float')

In [128]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          243 non-null    int64
 1   month        243 non-null    int64
 2   year         243 non-null    int64
 3   Temperature  243 non-null    int64
 4   RH           243 non-null    int64
 5   Ws           243 non-null    int64
 6   Rain         243 non-null    float64
 7   FFMC         243 non-null    float64
 8   DMC          243 non-null    float64
 9   DC           243 non-null    float64
 10  ISI          243 non-null    float64
 11  BUI          243 non-null    float64
 12  FWI          243 non-null    float64
 13  Classes      243 non-null    str
 14  Region       243 non-null    int64
dtypes: float64(7), int64(7), str(1)
memory usage: 30.7 KB

## Save the clean Dataset

In [129]:
dataset.to_csv('./CLEANED_Algerian_forest_fires_dataset_UPDATE.csv', index=False)